### @name="Get all products"
GET http://localhost:8080/api/products
Accept: application/json

### @name="Get product by ID"
GET http://localhost:8080/api/products/3
Accept: application/json

### @name="Get product by ID which doesn't exist"
GET http://localhost:8080/api/products/43
Accept: application/json


### @name="Get products by Range"
GET http://localhost:8080/api/products?low=500&high=15000
Accept: application/json

### @name="Add Product"
POST http://localhost:8080/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "Konfo Massage Chair",
  "price": 21000.00,
  "quantity": 50
}

### @name="update product price"
PATCH http://localhost:8080/api/products/5?price=1200.34
Accept: application/json
